#!/usr/bin/env bash


# Create a VPC
VPC_ID=$(aws ec2 create-vpc \
--cidr-block 172.1.0.0/16 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=MyVPC}]' \
--region ca-central-1 \
--query Vpc.VpcId \
--output text)

echo "VPC_ID:$VPC_ID"

# Trun on DNS hostnames
aws ec2 modify-vpc-attribute \
--vpc-id $VPC_ID \
--enable-dns-hostnames "{\"Value\":true}" \
--region ca-central-1

# Create an IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text)

echo "IGW_ID:$IGW_ID"
# Attach the IGW to the VPC
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID --region ca-central-1
#Create a new subnet

SUBNET_ID=$(aws ec2 create-subnet --vpc-id $VPC_ID \
--cidr-block 172.1.0.0/20 \
--query Subnet.SubnetId \
--output text)

echo "SUBNET_ID:$SUBNET_ID"
## auto assign IPv4 addresses
aws ec2 modify-subnet-attribute \
--subnet-id $SUBNET_ID \
--map-public-ip-on-launch \
--region ca-central-1

# Expicty assocaite subnet
RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query "RouteTables[0].RouteTableId" \
--output text)


echo "RT_ID:$RT_ID"

ASSOC_ID=$(aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID \
--query "AssociationId" \
--output text)

echo "ASSOC_ID:$ASSOC_ID"

# Add a route for our RT to our IGW

aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID 


echo "./delete_vpc $VPC_ID $IGW_ID $SUBNET_ID $ASSOC_ID $RT_ID"