#!/usr/bin/env bash

# VPC IGW SUBNET RT

if [ -z "$1" ]; then
  echo "VPC_ID not provided"
else
  export VPC_ID="$1"
fi

if [ -z "$2" ]; then
  echo "IGW_ID not provided"
else
  export IGW_ID="$2"
fi

if [ -z "$3" ]; then
  echo "SUBNET_ID not provided"
else
  export SUBNET_ID="$3"
fi
if [ -z "$4" ]; then
  echo "ASSOC_ID not provided"
else
  export ASSOC_ID="$4"
fi
if [ -z "$5" ]; then
  echo "RT_ID not provided"
else
  export RT_ID="$5"
fi
# Detach the IGW
aws ec2 detach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID \
--region ca-central-1

# Delete IGW
aws ec2 delete-internet-gateway \
--internet-gateway-id $IGW_ID \
--region ca-central-1


echo "ASSOC_ID:$ASSOC_ID"

aws ec2 disassociate-route-table \
--association-id $ASSOC_ID \
--region ca-central-1

# Delete Subnet
aws ec2 delete-subnet \
--subnet-id $SUBNET_ID \
--region ca-central-1


# Delete Route Table
# aws ec2 delete-route-table \
# --route-table-id $RT_ID \
# --region ca-central-1

# Delete VPC
aws ec2 delete-vpc \
--vpc-id $VPC_ID \
--region ca-central-1


