#!/usr/bin/env bash
echo "== delete object =="

set -e

# check for bucket name
if [ -z "$1" ]; then 
  echo "there needs to be a bucket name eg. ./delete-object my-bucket-name filename" 
  exit 1 
fi 

# check for filename
if [ -z "$2" ]; then 
  echo "there needs to be a filename eg. ./delete-object my-bucket-name filename" 
  exit 1 
fi 

BUCKET_NAME=$1
OBJECT_KEY=$2

aws s3api delete-object \
  --bucket "$BUCKET_NAME" \
  --key "$OBJECT_KEY"
