#!/usr/bin/env bash

echo "== deploy sns"

STACK_NAME="sns-basic"

aws cloudformation deploy \
  --template-file template.yaml \
  --stack-name $STACK_NAME \
  --region us-east-1 \
  --capabilities CAPABILITY_IAM