#https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html
AWSTemplateFormatVersion: 2010-09-09
Description: A sample s3 bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
      # 不指定 BucketName，AWS 會自動生成唯一名稱
